"""initial

Revision ID: 738d5dcc499c
Revises: 
Create Date: 2026-03-25 21:33:29.395253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738d5dcc499c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile_no', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin'), nullable=True),
    sa.Column('email_verified', sa.Integer(), nullable=True),
    sa.Column('mobile_verified', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_no')
    )
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.Enum('email', 'mobile'), nullable=False),
    sa.Column('target_value', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('is_verified', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cbc_Reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cbc_json', sa.JSON(), nullable=True),
    sa.Column('interpretation_json', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Patient_Reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('glucose', sa.Float(precision=2), nullable=True),
    sa.Column('blood_pressure', sa.Float(precision=2), nullable=True),
    sa.Column('skin_thickness', sa.Float(precision=2), nullable=True),
    sa.Column('insulin', sa.Float(precision=2), nullable=True),
    sa.Column('bmi', sa.Float(precision=2), nullable=True),
    sa.Column('diabetes_pedigree_function', sa.Float(precision=4), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('diabetes_prediction', sa.String(length=64), nullable=True),
    sa.Column('hypertension_prediction', sa.String(length=64), nullable=True),
    sa.Column('heart_disease_prediction', sa.String(length=64), nullable=True),
    sa.Column('risk_level', sa.String(length=64), nullable=True),
    sa.Column('abnormal_count', sa.Integer(), nullable=True),
    sa.Column('abnormal_json', sa.JSON(), nullable=True),
    sa.Column('conditions_json', sa.JSON(), nullable=True),
    sa.Column('specialists_json', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Patient_Reports')
    op.drop_table('Cbc_Reports')
    op.drop_table('verification_codes')
    op.drop_table('users')
    # ### end Alembic commands ###
